import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import { Header } from "@/components/layout/Header";
import { yellowCardGlass } from "@/variants/glassmorphism";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <Image
          src="/images/background.webp"
          alt="background"
          width={1980}
          height={800}
          className="absolute top-0 left-0  w-full h-full z-[-1]  object-cover opacity-75 filter "
        />
        <div
          className="absolute left-[3vw] w-[94vw]  z-[-1] h-[94vh] top-[3vh]"
          style={yellowCardGlass}
        ></div>
        <div className="overflow-scroll max-h-[100vh]">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
